### ISSUE TITLE
rokuDeploy is not a function

### ISSUE THREAD

**Issue by pajtai** [TwitchBronBron/roku-deploy#1]
Error: `TypeError: rokuDeploy is not a function`

Code:

```
const rokuDeploy = require('roku-deploy');
const configs = require('../rokudeploy.json');


rokuDeploy(configs)
  .then(() => console.log('deployed'))
  .catch((e) => console.log(e));
```

Note that `npm run deploy` runs with no errors with package.json:

```
  "scripts": {
    "deploy": "roku-deploy"
  }
```

**Comment by TwitchBronBron** [comment]
The 'roku-deploy' module is actually made up of several functions. When you run it from the command line, it actually calls `rokuDeploy.deploy`; 

What you probably want is this:

```
const deploy = require('roku-deploy').deploy;
...

**Comment by TwitchBronBron** [comment]
@pajtai did solve your issue?

**Comment by pajtai** [comment]
@TwitchBronBron yup, thanks!

**Comment by TwitchBronBron** [comment]
@pajtai I just realized that the readme was wrong, which is why you asked this question in the first place. My bad! I updated the readme to correctly show how to use the library.

**Comment by pajtai** [comment]
Thanks @TwitchBronBron !
