### ISSUE TITLE
Add Signed Package Creation

### ISSUE THREAD

**Issue by triwav** [TwitchBronBron/roku-deploy#8]
Currently roku-deploy doesn't handle anything other than doing a regular deployment to the device while developing. In order to help make this the base for a more formalized CI/CD script we need to at minimum be able to make a signed package file for upload to Roku as well. Being able to switch Dev ID would be nice as well but is not required.

**Comment by TwitchBronBron** [comment]
Not sure if the "username" field is what you mean by Dev ID, but if so, then that's already supported? https://github.com/TwitchBronBron/roku-deploy/blob/d7dceeecb5d25c239b3cebf3c982dddcc5ec0eaa/src/index.ts#L599

**Comment by triwav** [comment]
No referring to actually being able to change what dev ID you're signing with. You can rekey a device by providing a package that was signed with it as well at the password. Some people work on multiple projects with different dev IDs and that would simplify and hopefully also help reduce errors as well. Again just a nice to have.

**Comment by TwitchBronBron** [comment]
Gotcha. Ok cool, sounds good.
